wandb_version: 1

LR:
  desc: null
  value: 0.001
NUM_EPOCHS:
  desc: null
  value: 30
BATCH_SIZE:
  desc: null
  value: 16
MODEL_PTH:
  desc: null
  value: resnet101.pth
NUM_CLASSES:
  desc: null
  value: 62
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.10.9
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1707736700.748001
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 63
      - 105
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.16.3
      6: 4.24.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
